version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: ipfs/go-ipfs
    steps:
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - checkout
      - run:
          name: Waiting for IPFS to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5001 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for IPFS && exit 1

      - run: curl 'http://127.0.0.1:5001/api/v0/swarm/connect?arg=/ip4/94.130.135.167/tcp/4002/ws/ipfs/QmUEMvxS2e7iDrereVYc5SWPauXPyNwxcy9BXZrC1QTcHE'
      - run: printf '/ip4/127.0.0.1/tcp/5001' > /tmp/api
      - run:
          environment:
            IPFS_PATH: /tmp
          command: go test -v ./...
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
